---
AWSTemplateFormatVersion: 2010-09-09
Description: "Cloudtrail Alarms (rev:3)"

#====================================================================================================
Parameters:
#====================================================================================================
  CloudTrailLogGroupName:
    Type: String
    Description: CloudTrail log group name when CloudTrail is already provisioned
  AlarmNotificationTopic:
    Type: String
    Description: SNS Notification Topic to send alarms to

#====================================================================================================
Resources:
#====================================================================================================

  RootAccountUsageMetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: !Ref CloudTrailLogGroupName
      FilterPattern: '{$.userIdentity.type="Root" && $.userIdentity.invokedBy NOT EXISTS && $.eventType !="AwsServiceEvent"}'
      MetricTransformations:
        - MetricNamespace: CloudTrailMetrics
          MetricName: RootAccountUsageEventCount
          MetricValue: '1'
  
  RootAccountUsageLogInsight:
    Type: 'AWS::Logs::QueryDefinition'
    Properties:
      LogGroupNames:
        - !Ref CloudTrailLogGroupName
      Name: RootAccountUsage
      QueryString: |
        fields @timestamp, userIdentity.principalId 
        | sort @timestamp desc 
        | filter userIdentity.type="Root" and ispresent(userIdentity.invokedBy) and eventType !="AwsServiceEvent"

  RootAccountUsageAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: RootAccountUsage
      AlarmDescription: (CIS-3.3) Alarms when Root Account is used
      AlarmActions:
        - !Ref AlarmNotificationTopic
      MetricName: RootAccountUsageEventCount
      Namespace: CloudTrailMetrics
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  NoMFALoginUsageMetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: !Ref CloudTrailLogGroupName
      FilterPattern: '{ ($.eventName ="ConsoleLogin") && ($.additionalEventData.MFAUsed != "Yes") && ($.userIdentity.type != "AssumedRole") }'
      MetricTransformations:
        - MetricNamespace: CloudTrailMetrics
          MetricName: NoMFALoginEventCount
          MetricValue: '1'
  
  NoMFALoginUsageLogInsight:
    Type: 'AWS::Logs::QueryDefinition'
    Properties:
      LogGroupNames:
        - !Ref CloudTrailLogGroupName
      Name: NoMFALoginUsage
      QueryString: |
        fields @timestamp, userIdentity.principalId 
        | sort @timestamp desc 
        | filter eventName ="ConsoleLogin" and additionalEventData.MFAUsed != "Yes" and userIdentity.type != "AssumedRole"

  NoMFALoginUsageAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: NoMFALogin
      AlarmDescription: Monitoring for single-factor console logins will increase visibility into accounts that are not protected by MFA.
      AlarmActions:
        - !Ref AlarmNotificationTopic
      MetricName: NoMFALoginEventCount
      Namespace: CloudTrailMetrics
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
